// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.Wipers;

import edu.wpi.first.wpilibj2.command.Command;

import java.lang.System.Logger.Level;
import java.util.function.DoubleSupplier;

import javax.lang.model.util.ElementScanner14;

import frc.robot.RobotContainer;
import frc.robot.subsystems.AlgaeIntake;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.ElevatorAndArm;
import frc.robot.subsystems.ElevatorAndArm.ElevAndArmPos;
import frc.robot.subsystems.Wipers.GuidePos;
import frc.robot.subsystems.Wipers.Wiper;
import frc.robot.subsystems.Wipers;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class WipersCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private Wipers m_Wipers;
    private boolean bDone = false;
    private double m_NewPos;
    private Wipers.Wiper wiper;
    private Wipers.GuidePos newPos = GuidePos.START;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public WipersCmd(Wipers.Wiper tWiper) {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        wiper = tWiper;
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_Wipers = RobotContainer.getInstance().m_Wipers;
        addRequirements(m_Wipers);
        if (wiper == Wipers.Wiper.LEFT && m_Wipers.leftTarget == Wipers.GuidePos.START) {
            m_Wipers.setLeftCmdPos(Wipers.GuidePos.OUT);
            newPos = Wipers.GuidePos.OUT;
            m_Wipers.leftTarget = Wipers.GuidePos.OUT;
        } else if (wiper == Wipers.Wiper.LEFT && m_Wipers.leftTarget == Wipers.GuidePos.OUT) {
            m_Wipers.setLeftCmdPos(GuidePos.START);
            newPos = Wipers.GuidePos.START;
            m_Wipers.leftTarget = Wipers.GuidePos.START;

        }
        if (wiper == Wipers.Wiper.RIGHT && m_Wipers.rightTarget == Wipers.GuidePos.START) {
            m_Wipers.setRightCmdPos(GuidePos.OUT);
            newPos = Wipers.GuidePos.OUT;
            m_Wipers.rightTarget = Wipers.GuidePos.OUT;
        } else if (wiper == Wipers.Wiper.RIGHT && m_Wipers.rightTarget == Wipers.GuidePos.OUT) {
            m_Wipers.setRightCmdPos(GuidePos.START);
            newPos = Wipers.GuidePos.START;
            m_Wipers.rightTarget = Wipers.GuidePos.START;

        }

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        if (wiper == Wipers.Wiper.LEFT) {
            bDone = m_Wipers.isLeftAtTarget(newPos);
        }
        if (wiper == Wipers.Wiper.RIGHT) {
            bDone = m_Wipers.isRightAtTarget(newPos);
        }

        if (bDone == true) {
            end(false);
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return bDone;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
